### ISSUE TITLE
Force Close when Sign in

### ISSUE THREAD

**Issue by yogabayusavira** [alfianyusufabdullah/ChatYuk#8]
Setelah Register langsung masuk ke aplikasinya sendiri tanpa login, saat di sign out dan sign in lagi akan terjadi crash. 
Apa aja yang di enable di Firebase console bang?

**Comment by alfianyusufabdullah** [comment]
@redbluesky21 Skenarionya memang Register -> Halaman Chat. Untuk Sign In memang force close karena ada kesalahan _named argument_ dipemanggilan fungsi `doLogin`.

Untuk yang di Firebase Console yang diaktifin cukup metode email/password

**Comment by redbluesky21** [comment]
Skenario chatnya bagaimana gan? belum berhasil nyoba dari 2 handphone.
